version: "3"
services:
  app-vue-laravel:
    build: .
    image: app-vue-laravel
    container_name: app-vue-laravel
    volumes:
    - ./application:/application
    ports:
    - 9001:9001
    networks:
      - bubble

networks:
  bubble:
    external: true