version: "3"
services:
  app-clients-admin:
    build: .
    image: app-clients-admin
    container_name: app-clients-admin
    volumes:
    - ./application:/application
    ports:
    - 9001:9001
    networks:
      - bubble

networks:
  bubble:
    external: true